### ISSUE TITLE
Filter from Graphcool API causes self-referential type & thus compilation error

### ISSUE THREAD

**Issue by nicolasartman** [dillonkearns/graphqelm#24]
First, thank you for making such an awesome library & tool! I'm really excited to start using this on a side project of mine that uses https://www.graph.cool's hosted API system for the backend, but there's one small snag I noticed.

When I generate the code for my API via `graphqelm https://api.graph.cool/simple/v1/cj1rh31pc8ykf0127fwssmw32 --base API`, some of the generated filters seem to reference themselves and this causes compilation to fail. For example, in UserFilter.elm, it generates:

```
type alias UserFilter =
    { and : OptionalArgument (List API.InputObject.UserFilter.UserFilter), or : OptionalArgument (List API.InputObject.UserFilter.UserFilter), .............
```

which I think references that type alias itself in its definition. The exact error message is "Cannot find type `API.InputObject.UserFilter.UserFilter`.

If there's anything more I can do to help replicate this issue or look into it further, please let me know and I'll be more than happy to do so!

**Comment by dillonkearns** [comment]
Hello @nicolasartman, thank you so much for reporting the issue! This should be a pretty simple fix, I'll push something to address it soon.

**Comment by dillonkearns** [comment]
@nicolasartman in the meantime, as a workaround if you simply do a find and replace of `API.InputObject.UserFilter.UserFilter` => `UserFilter` within `UserFilter.elm` that will get you past that compilation error.

I'll get to this soon but hopefully that helps until then!

**Comment by Frozen666** [comment]
@dillonkearns This workaround fixes the "Cannot find type ..." error message, unfortunately it leads to a recursive type alias (see here: https://github.com/elm-lang/elm-compiler/blob/master/hints/recursive-alias.md).

**Comment by Frozen666** [comment]
I posted a somewhat related problem concerning the graph.cool APIs on the slack channel already. Those filters will also reference the filters of their relation objects, which in turn reference the starting filter, leading to circular dependencies. This can be seen using the API https://api.graph.cool/simple/v1/cjct1ri2d0twa0114q7ld4xqu, where InputObject.Postfilter imports InputObject.CommentFilter and vice versa

**Comment by dillonkearns** [comment]
@Frozen666 ah, indeed you're correct, with the workaround there are still issues. Thanks for reporting back with that, that saved me some time.

What the code generation needs to do is generate union types (with just a single tag) instead of type aliases. And because of the issue you mention of the circular dependencies, I will need to generate all these types inside of a single file, that way no imports are needed so there is no circular dependency issue. Not too complicated, actually.

**Comment by dillonkearns** [comment]
@Frozen666 @nicolasartman I published a fix for this in npm version 3.0.0! I've got some pretty extensive tests and it's looking good.

I'll leave this open a bit and wait to hear that everything is looking good in case I missed a case in my end-to-end tests. Thanks again to both of you for reporting this issue!

**Comment by nicolasartman** [comment]
Fantastic! I’ll check this out tonight and will let you know. Thanks so
much!

**Comment by nicolasartman** [comment]
Sorry for the delay @dillonkearns—I just tested this against my initial API and it's _really_ close I think, but there's one error remaining. For the User object (and only that one it seems), it generates two functions with the same name:
```
{-|

  - auth0UserId -
  - id -
-}
user : ({ auth0UserId : OptionalArgument String, id : OptionalArgument API.Scalar.Id } -> { auth0UserId : OptionalArgument String, id : OptionalArgument API.Scalar.Id }) -> SelectionSet decodesTo API.Object.User -> Field (Maybe decodesTo) RootQuery
user fillInOptionals object =
    let
        filledInOptionals =
            fillInOptionals { auth0UserId = Absent, id = Absent }

        optionalArgs =
            [ Argument.optional "auth0UserId" filledInOptionals.auth0UserId Encode.string, Argument.optional "id" filledInOptionals.id (\(API.Scalar.Id raw) -> Encode.string raw) ]
                |> List.filterMap identity
    in
        Object.selectionField "User" optionalArgs object (identity >> Decode.maybe)
user : SelectionSet decodesTo API.Object.User -> Field (Maybe decodesTo) RootQuery
user object =
    Object.selectionField "user" [] object (identity >> Decode.maybe)
```

This, as expected, fails compilation due to top-level identifier ambiguity.

**Comment by dillonkearns** [comment]
Hey @nicolasartman, thank you for reporting back! This is a separate issue so I've created #34 to discuss this problem. Would you mind giving your feedback there? I'll close this one as it appears to be fixed from your account and @Frozen666's.

Thanks again for helping me track this down!
